# Generated by Django 3.2.4 on 2021-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delySantiago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(null=True, upload_to='platos'),
        ),
    ]
