# Generated by Django 3.2.4 on 2021-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delySantiago', '0002_plato_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
