# Generated by Django 3.2.4 on 2021-06-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('ingredientes', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='platos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Registro.proveedor')),
            ],
        ),
    ]
